GET http://localhost:3333/users
###
GET http://localhost:3333/users/me
###
POST http://localhost:3333/users
Content-Type: application/json

{
  "username":"Test",
  "first_name":"Test",
  "last_name":"Test",
  "email":"test@mail.com"
}
###
DELETE http://localhost:3333/users/1
###
PUT http://localhost:3333/users/1
Content-Type: application/json

{
  "username":"Test",
  "first_name":"Test1",
  "last_name":"Test1",
  "email":"test@mail.com"
}
###
PATCH http://localhost:3333/users/1
Content-Type: application/json

{
  "username":"Test"
}
###
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "username":"Wens",
  "password":"12345"
}
###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "username":"Wens",
  "password":"12345"
}
###
GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZWF0IjoxNzMwMjc2NTM3LCJpYXQiOjE3MzAyNzY0Nzd9LCJzZXNzaW9uIjoiNzY2YzQwY2MtMTQ2MC01YjRmLThkYTMtYzkyMDA3NjFlMDczIn0.M8uc9HDcIEi-D_hoyNo43UxhMacTZtvcWME9NnaP2pk